default_install_hook_types: ['pre-commit', 'pre-push']
default_stages: [pre-commit]


exclude: >
  jira_telegram_bot/use_cases/prompts.py


repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-ast
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: debug-statements
      - id: end-of-file-fixer
        exclude_types: [svg, plain-text]
      - id: trailing-whitespace
        exclude_types: [svg]
      - id: check-added-large-files
      - id: check-shebang-scripts-are-executable
      - id: mixed-line-ending
  - repo: https://github.com/asottile/add-trailing-comma
    rev: v3.1.0
    hooks:
      - id: add-trailing-comma
  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        exclude: ^(.+)\/migrations\/(.+)$|prompts\.py$
        stages: [commit]
        args: [
          --tee,
          --format=gl-codeclimate,
          --output-file=flake8-code-quality-report.json,
          --max-line-length=130,
          --extend-immutable-calls=self.deps.depends
        ]
        additional_dependencies: [
          flake8-mutable,
          flake8-gl-codeclimate,
          flake8-bugbear,
          flake8-comprehensions,
          flake8-print,
          flake8-simplify,
          flake8-django,
        ]
  - repo: https://github.com/asottile/reorder-python-imports
    rev: v3.12.0
    hooks:
      - id: reorder-python-imports
        exclude: ^(pre_commit/resources/|testing/resources/python3_hooks_repo/)
        args: [--py39-plus, --add-import, 'from __future__ import annotations']
  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black
        language_version: python3
        exclude: ^(.+)\/migrations\/(.+)$
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.32.0
    hooks:
      - id: yamllint
        exclude: '\.gitlab-ci\.yml'
  - repo: https://gitlab.com/bmares/check-json5
    rev: v1.0.0
    hooks:
      - id: check-json5
  - repo: local
    hooks:
      - id: check-version
        name: Check Version
        stages: [commit]
        entry: python3 jira_telegram_bot/utils/check_version.py
        language: python
        files: jira_telegram_bot/__init__.py$
        pass_filenames: false
        always_run: true
