version: '3.8'

services:
  telegram-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: telegram_bot
    image: jira_telegram_bot:v3
    volumes:
      - .:/app
    command: >
      python3 jira_telegram_bot
    restart: always
  
  synth-pm-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: synth_pm_api
    image: jira_telegram_bot:v3
    volumes:
      - .:/app
    command: >
      python3 jira_telegram_bot/frameworks/api/main.py
    restart: always
    ports:
      - "2318:2318"

  ticketing-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ticketing_bot
    volumes:
      - .:/app
    command: >
      python3 jira_telegram_bot/frameworks/fast_api/create_ticket.py
    restart: always
    ports:
      - "2315:2315"

  jira-report-scheduler:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jira_report_scheduler
    image: jira_telegram_bot:v3
    volumes:
      - .:/app
    command: >
      python3 scripts/run_scheduled_reports.py
    restart: always
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432

  # synth-pm-service:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: synth_pm
  #   image: jira_telegram_bot:v3
  #   volumes:
  #     - .:/app
  #   command: >
  #     python3 scripts/run_synth_pm.py service
  #   restart: always
  #   environment:
  #     - POSTGRES_HOST=postgres
  #     - POSTGRES_PORT=5432
  

  deadline-notifier:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: deadline_notifier
    image: jira_telegram_bot:v3
    volumes:
      - .:/app
    command: >
      python3 jira_telegram_bot/frameworks/scheduler/cron_job.py
    restart: always