"""Constants package."""
from jira_telegram_bot.entities.constants.persian_messages import (
    TASK_NOT_STARTED,
    HOURS_TODAY,
    WORKLOG_MISSING,
    DELAY_WAITING_APPROVAL,
    DELAY_TECHNICAL_BLOCKER,
    DELAY_OTHER_PRIORITIES,
    DELAY_MISSING_REQUIREMENTS,
    DELAY_DEPENDENCY_NOT_READY,
    DELAY_OTHER,
    REQUEST_SUBTASKS,
    SKIP_TASK,
    FINISH_LATER,
    CHECK_PAUSED,
    HOURS_1,
    HOURS_2,
    HOURS_3,
    HOURS_4,
    HOURS_6,
    HOURS_8,
    HOURS_CUSTOM,
    ENTER_CUSTOM_HOURS,
    ENTER_CUSTOM_DELAY_REASON,
    WORKLOG_RECORDED,
    DELAY_RECORDED,
    HOURS_RECORDED,
    SUBTASK_REQUEST_SENT,
    TASK_SKIPPED,
    DAILY_TASK_CHECK_TITLE,
    STATUS_REGRESSION_MESSAGE,
    PO_SUBTASK_REQUEST,
    THANK_YOU,
    ERROR_MESSAGE,
    DAILY_CHECK_START,
    DAILY_CHECK_COMPLETE,
    REASON_TEXT,
    TASK_HEADER,
    TASK_HEADER_WITH_DATES,
    TASK_SPRINT,
    TASK_DESCRIPTION,
)

# Re-export constants that are defined in parent constants.py
# This is used by existing code that imports from this __init__.py
import sys
import importlib.util

# Load constants.py directly to avoid circular import
spec = importlib.util.spec_from_file_location(
    "base_constants",
    __file__.replace("constants/__init__.py", "constants.py")
)
base_constants = importlib.util.module_from_spec(spec)
spec.loader.exec_module(base_constants)

# Re-export all constants from constants.py to avoid breaking existing imports
DEV_ISSUE_TYPES = base_constants.DEV_ISSUE_TYPES
BUG_ISSUE_TYPES = base_constants.BUG_ISSUE_TYPES
SUPPORT_LABELS = base_constants.SUPPORT_LABELS
SUPPORT_EPIC_NAME = base_constants.SUPPORT_EPIC_NAME
HIGH_PRIORITY = base_constants.HIGH_PRIORITY
REVIEW_STATUSES = base_constants.REVIEW_STATUSES
BACKLOG_STATUSES = base_constants.BACKLOG_STATUSES
DONE_STATUSES = base_constants.DONE_STATUSES
TESTER_LABEL = base_constants.TESTER_LABEL
DEFAULT_DEFECT_THRESHOLDS = base_constants.DEFAULT_DEFECT_THRESHOLDS
HIGH_PRIORITY_ZERO_COMPLETION_PENALTY = base_constants.HIGH_PRIORITY_ZERO_COMPLETION_PENALTY
HIGH_PRIORITY_BELOW_MIN_SCORE = base_constants.HIGH_PRIORITY_BELOW_MIN_SCORE
MAX_EARLY_DELIVERY_BONUS = base_constants.MAX_EARLY_DELIVERY_BONUS
EXTRA_TASK_COMPLETION_BONUS = base_constants.EXTRA_TASK_COMPLETION_BONUS
REQUIRED_TASKS_HOURS_RATIO = base_constants.REQUIRED_TASKS_HOURS_RATIO
DEADLINE_GRACE_PERIOD_DAYS = base_constants.DEADLINE_GRACE_PERIOD_DAYS
UNDELIVERED_TASK_DELAY_DAYS = base_constants.UNDELIVERED_TASK_DELAY_DAYS
PENALTY_COEFFICIENT_MAX = base_constants.PENALTY_COEFFICIENT_MAX
PENALTY_COEFFICIENT_MIN = base_constants.PENALTY_COEFFICIENT_MIN
PENALTY_COEFFICIENT_TASK_THRESHOLD = base_constants.PENALTY_COEFFICIENT_TASK_THRESHOLD
PRIORITY_WEIGHT_HIGHEST = base_constants.PRIORITY_WEIGHT_HIGHEST
PRIORITY_WEIGHT_HIGH = base_constants.PRIORITY_WEIGHT_HIGH
PRIORITY_WEIGHT_OTHERS = base_constants.PRIORITY_WEIGHT_OTHERS
TIME_REGISTRATION_THRESHOLD = base_constants.TIME_REGISTRATION_THRESHOLD
TIME_REGISTRATION_PENALTY_BASE = base_constants.TIME_REGISTRATION_PENALTY_BASE
TIME_REGISTRATION_PENALTY_MULTIPLIER = base_constants.TIME_REGISTRATION_PENALTY_MULTIPLIER
DEFAULT_WEEKLY_HOURS = base_constants.DEFAULT_WEEKLY_HOURS
DEFAULT_WORKDAYS = base_constants.DEFAULT_WORKDAYS
DEFAULT_TIMEZONE = base_constants.DEFAULT_TIMEZONE
EXPECTED_HOURS_WEEKLY = base_constants.EXPECTED_HOURS_WEEKLY
EXPECTED_HOURS_TOTAL = base_constants.EXPECTED_HOURS_TOTAL
DEPT_INFERENCE_COMPONENT = base_constants.DEPT_INFERENCE_COMPONENT
DEPT_INFERENCE_LABEL = base_constants.DEPT_INFERENCE_LABEL
DEPT_INFERENCE_USER_CONFIG = base_constants.DEPT_INFERENCE_USER_CONFIG

__all__ = [
    "TASK_NOT_STARTED",
    "HOURS_TODAY",
    "WORKLOG_MISSING",
    "DELAY_WAITING_APPROVAL",
    "DELAY_TECHNICAL_BLOCKER",
    "DELAY_OTHER_PRIORITIES",
    "DELAY_MISSING_REQUIREMENTS",
    "DELAY_DEPENDENCY_NOT_READY",
    "DELAY_OTHER",
    "REQUEST_SUBTASKS",
    "SKIP_TASK",
    "FINISH_LATER",
    "CHECK_PAUSED",
    "HOURS_1",
    "HOURS_2",
    "HOURS_3",
    "HOURS_4",
    "HOURS_6",
    "HOURS_8",
    "HOURS_CUSTOM",
    "ENTER_CUSTOM_HOURS",
    "ENTER_CUSTOM_DELAY_REASON",
    "WORKLOG_RECORDED",
    "DELAY_RECORDED",
    "HOURS_RECORDED",
    "SUBTASK_REQUEST_SENT",
    "TASK_SKIPPED",
    "DAILY_TASK_CHECK_TITLE",
    "STATUS_REGRESSION_MESSAGE",
    "PO_SUBTASK_REQUEST",
    "THANK_YOU",
    "ERROR_MESSAGE",
    "DAILY_CHECK_START",
    "DAILY_CHECK_COMPLETE",
    "REASON_TEXT",
    "TASK_HEADER",
    "TASK_HEADER_WITH_DATES",
    "TASK_SPRINT",
    "TASK_DESCRIPTION",
    # Re-exported constants from constants.py
    "DONE_STATUSES",
    "DEFAULT_WEEKLY_HOURS",
    "DEADLINE_GRACE_PERIOD_DAYS",
    "DEFAULT_WORKDAYS",
    "DEFAULT_TIMEZONE",
    "DEFAULT_DEFECT_THRESHOLDS",
    "EXPECTED_HOURS_WEEKLY",
    "EXPECTED_HOURS_TOTAL",
    "DEPT_INFERENCE_COMPONENT",
    "DEPT_INFERENCE_LABEL",
    "DEPT_INFERENCE_USER_CONFIG",
]
