apiVersion: apps/v1
kind: Deployment
metadata:
  name: physo-farsi-admin
  labels:
    app: physo-farsi-admin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: physo-farsi-admin
  template:
    metadata:
      labels:
        app: physo-farsi-admin
    spec:
      imagePullSecrets:
      - name: hub-hooshdev
      containers:
      - name: physo-farsi-admin
        image: hub.hooshdev.ir/physo/physo_farsi_admin
        ports:
        - containerPort: 8282
        resources:
          requests:
            memory: "128M"
            cpu: "250m"
          limits:
            memory: "128M"
            cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: physo-farsi-admin-service
spec:
  #type: NodePort
  type: ClusterIP
  selector:
    app: physo-farsi-admin
  ports:
  - protocol: TCP
    port: 8282
    targetPort: 8282
      #nodePort: 30082  # Change as needed (NodePorts range from 30000-32767)
